using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace BevyDotNet.Generators;

/*
Kurgumuzda önemli bir problem var. N sayıda Component'in işin içerisine katılmak istendiği
senaryolarda, Query ve ISystem gibi enstrümanları generic parametre sayısına göre çoklamam gerekiyor.
Oyun programcısının sisteme ne kadar bileşen göndereceği belirsiz. 
İlk aşamada bu versiyonları belli bir sayıya kadar otomatik olarak üretecek bir Source Generator ele alabiliriz.

Bu generator System Interface'lerin, Query sınıflarını ve Scheduler sınıfının çoklanan Add gibi metotlarını üretebilir.

Dikkat: Bu kod üreticisini yazdıktan sonra build aşamasında var olan kodlarla çakışmalar olur. Bu yüzden;

- ISystem<> ve Query<> elemanlarını silmeliyiz.
- Ayrıca Scheduler sınıfının AddSystem metotlarını da silmeliyiz.
- Scheduler'ı partial olarak işaretlemeliyiz. (public partial class Scheduler)
 */
[Generator(LanguageNames.CSharp)]
public class EcsGenerator : IIncrementalGenerator
{
    private const int MaxComponentCount = 8;

    // System Interface türlerinin üretimi için yardımcı metot
    // Aslında var olan System interface kod bloklarının StringBuilder yardımıyla belirtilen bileşen sayısına göre ürettiriryoruz.
    private static string GenerateSystemInterface()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("namespace BevyDotNet.Library;");
        builder.AppendLine();

        for (int i = 1; i <= MaxComponentCount; i++)
        {
            var typeParameters = string.Join(", ", Enumerable.Range(1, i).Select(n => $"T{n}"));
            var constraints = string.Join(" ", Enumerable.Range(1, i).Select(n => $"where T{n} : IComponent"));
            var tupleArgs = string.Join(", ", Enumerable.Range(1, i).Select(n => $"T{n} component{n}"));

            builder.AppendLine($"public interface ISystem<{typeParameters}> {constraints}");
            builder.AppendLine("{");
            builder.AppendLine($"    void Apply(IEnumerable<(Entity entity, {tupleArgs})> components);");
            builder.AppendLine("}");
            builder.AppendLine();
        }
        return builder.ToString();
    }

    /*
        Query<T1,T2> sınıfında iç içe SelectMany kullanıyoruz.
        İki seviye için kolay ancak burada ilgili kod bloğunu generator'a ürettirmemiz lazım.
        Onun için kullanılan yardımcı metot.
    */
    private static string BuildSelectMany(int componentCount, int level = 1)
    {
        if (level == componentCount)
        {
            var tupleArgs = string.Join(", ", Enumerable.Range(1, componentCount).Select(i => $"c{i}"));
            return $"e.Components.OfType<T{level}>().Select(c{level} => (e, {tupleArgs}))";
        }

        return $"e.Components.OfType<T{level}>().SelectMany(c{level} => {BuildSelectMany(componentCount, level + 1)})";
    }

    /*
     Burası da Query<T1,T2... T8>  sınıflarının üretimi için kullanılan yardımcı metot.
     Düşünce yapımız şu; var olan Query sınıfından bileşen sayısına göre n tane Query sınıfı ürettirmek.
     StringBuilder ile gerekli tasarımı generator'a yaptırıyoruz.
     
     */
    private static string GenerateQuery()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace BevyDotNet.Library;");
        builder.AppendLine();

        for (var i = 1; i <= MaxComponentCount; i++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, i).Select(n => $"T{n}"));
            var constraints = string.Join(" ", Enumerable.Range(1, i).Select(n => $"where T{n} : IComponent"));
            var tupleArgs = string.Join(", ", Enumerable.Range(1, i).Select(n => $"T{n} component{n}"));

            builder.AppendLine($"public class Query<{typeParams}> {constraints}");
            builder.AppendLine("{");
            builder.AppendLine("    private readonly World _world;");
            builder.AppendLine("    public Query(World world) => _world = world;");
            builder.AppendLine();
            builder.AppendLine($"    public IEnumerable<(Entity entity, {tupleArgs})> GetEntities()");
            builder.AppendLine("    {");
            builder.AppendLine("        return _world.GetEntities()");
            builder.AppendLine($"            .SelectMany(e => {BuildSelectMany(i)});");
            builder.AppendLine("    }");
            builder.AppendLine("}");
            builder.AppendLine();
        }

        return builder.ToString();
    }

    /*
     Tabii birde Scheduler içerisinde bileşen sayısına göre farklı şekillerde ele almak zorunda kaldığımız kısımlar var.
     Add metotları ve Run metodu içerisinde Apply çağrısı gibi. Bunları da generator ile ürettiriyoruz.
     */
    private static string GenerateSchedulerPart()
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("namespace BevyDotNet.Library;");
        builder.AppendLine();
        builder.AppendLine("public partial class Scheduler");
        builder.AppendLine("{");

        builder.AppendLine("    internal static readonly Type[] GeneratedSystemInterfaces =");
        builder.AppendLine("    {");
        for (var i = 1; i <= MaxComponentCount; i++)
            builder.AppendLine($"        typeof(ISystem<{new string(',', i - 1)}>),");
        builder.AppendLine("    };");
        builder.AppendLine();

        builder.AppendLine("    internal static readonly Type[] GeneratedQueryTypes =");
        builder.AppendLine("    {");
        for (var i = 1; i <= MaxComponentCount; i++)
            builder.AppendLine($"        typeof(Query<{new string(',', i - 1)}>),");
        builder.AppendLine("    };");
        builder.AppendLine();

        for (var i = 1; i <= MaxComponentCount; i++)
        {
            var typeParams = string.Join(", ", Enumerable.Range(1, i).Select(j => $"T{j}"));
            var constraints = string.Join(" ", Enumerable.Range(1, i).Select(j => $"where T{j} : IComponent"));

            builder.AppendLine($"    public void AddSystem<{typeParams}>(SystemState state, ISystem<{typeParams}> system) {constraints}");
            builder.AppendLine("    {");
            builder.AppendLine("        _systems[state].Add(system);");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ISystem.g.cs", SourceText.From(GenerateSystemInterface(), Encoding.UTF8));
            ctx.AddSource("Query.g.cs", SourceText.From(GenerateQuery(), Encoding.UTF8));
            ctx.AddSource("Scheduler.AddSystem.g.cs", SourceText.From(GenerateSchedulerPart(), Encoding.UTF8));
        });
    }
}
