using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace BevyDotNet.Generators;

/*
Kurgumuzda önemli bir problem var. N sayıda Component'in işin içerisine katılmak istendiği
senaryolarda, Query ve ISystem gibi enstrümanları generic parametre sayısına göre çoklamam gerekiyor.
Oyun programcısının sisteme ne kadar bileşen göndereceği belirsiz. 
İlk aşamada bu versiyonları belli bir sayıya kadar otomatik olarak üretecek bir Source Generator ele alabiliriz.

Bu generator System Interface'lerin, Query sınıflarını ve Scheduler sınıfının çoklanan Add gibi metotlarını üretebilir.

Dikkat: Bu kod üreticisini yazdıktan sonra build aşamasında var olan kodlarla çakışmalar olur. Bu yüzden;

- ISystem<> ve Query<> elemanlarını silmeliyiz.
- Ayrıca Scheduler sınıfının AddSystem metotlarını da silmeliyiz.
- Scheduler'ı partial olarak işaretlemeliyiz. (public partial class Scheduler)
 */
[Generator(LanguageNames.CSharp)]
public class EcsGenerator : IIncrementalGenerator
{
    private const int MaxComponentCount = 8;

    private static string SystemInterfaceTemplate(int count)
    {
        var typeParams = string.Join(", ", Enumerable.Range(1, count).Select(i => $"T{i}"));
        var constraints = string.Join(" ", Enumerable.Range(1, count).Select(i => $"where T{i} : IComponent"));
        var tupleArgs = string.Join(", ", Enumerable.Range(1, count).Select(i => $"T{i} component{i}"));

        return $$"""
        public interface ISystem<{{typeParams}}> {{constraints}}
        {
            void Apply(IEnumerable<(Entity entity, {{tupleArgs}})> components);
        }


        """;
    }

    private static string GenerateSystemInterface()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace BevyDotNet.Library;");
        sb.AppendLine();

        for (var count = 1; count <= MaxComponentCount; count++)
            sb.Append(SystemInterfaceTemplate(count));

        return sb.ToString();
    }

    private static string BuildSelectMany(int componentCount, int level = 1)
    {
        if (level == componentCount)
        {
            var tupleArgs = string.Join(", ", Enumerable.Range(1, componentCount).Select(i => $"c{i}"));
            return $"e.Components.OfType<T{level}>().Select(c{level} => (e, {tupleArgs}))";
        }

        return $"e.Components.OfType<T{level}>().SelectMany(c{level} => {BuildSelectMany(componentCount, level + 1)})";
    }

    private static string GenerateQueryClasses()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace BevyDotNet.Library;");
        sb.AppendLine();

        for (var count = 1; count <= MaxComponentCount; count++)
            sb.Append(QueryClassTemplate(count));

        return sb.ToString();
    }

    private static string QueryClassTemplate(int count)
    {
        var typeParams = string.Join(", ", Enumerable.Range(1, count).Select(i => $"T{i}"));
        var constraints = string.Join(" ", Enumerable.Range(1, count).Select(i => $"where T{i} : IComponent"));
        var tupleArgs = string.Join(", ", Enumerable.Range(1, count).Select(i => $"T{i} component{i}"));
        var body = BuildSelectMany(count);

        return $$"""
        public class Query<{{typeParams}}> {{constraints}}
        {
            private readonly World _world;
            public Query(World world) => _world = world;

            public IEnumerable<(Entity entity, {{tupleArgs}})> GetEntities()
            {
                return _world.GetEntities()
                    .SelectMany(e => {{body}});
            }
        }


        """;
    }

    private static string GenerateSchedulerPart()
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace BevyDotNet.Library;");
        sb.AppendLine();
        sb.AppendLine("public partial class Scheduler");
        sb.AppendLine("{");

        sb.AppendLine("    internal static readonly Type[] GeneratedSystemInterfaces =");
        sb.AppendLine("    {");
        for (var count = 1; count <= MaxComponentCount; count++)
            sb.AppendLine($"        typeof(ISystem<{new string(',', count - 1)}>),");
        sb.AppendLine("    };");
        sb.AppendLine();

        sb.AppendLine("    internal static readonly Type[] GeneratedQueryTypes =");
        sb.AppendLine("    {");
        for (var count = 1; count <= MaxComponentCount; count++)
            sb.AppendLine($"        typeof(Query<{new string(',', count - 1)}>),");
        sb.AppendLine("    };");
        sb.AppendLine();

        for (var count = 1; count <= MaxComponentCount; count++)
            sb.Append(GenerateAddSystemMethods(count));

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateAddSystemMethods(int arity)
    {
        var typeParams = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));
        var constraints = string.Join(" ", Enumerable.Range(1, arity).Select(i => $"where T{i} : IComponent"));

        return $$"""
            public void AddSystem<{{typeParams}}>(SystemState state, ISystem<{{typeParams}}> system) {{constraints}}
            {
                _systems[state].Add(system);
            }

        """;
    }

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ISystem.g.cs", SourceText.From(GenerateSystemInterface(), Encoding.UTF8));
            ctx.AddSource("Query.g.cs", SourceText.From(GenerateQueryClasses(), Encoding.UTF8));
            ctx.AddSource("Scheduler.g.cs", SourceText.From(GenerateSchedulerPart(), Encoding.UTF8));
        });
    }
}
